class ThreeLettersText {
  final String text;
  ThreeLettersText(this.text);
}

List<ThreeLettersText> threeletters = [
  ThreeLettersText('And \n \n "Tom and John are good friends."'),
  ThreeLettersText('But \n \n "She asked him to stay but he had to go to work."'),
  ThreeLettersText('Car \n \n "The car colour is Black."'),
  ThreeLettersText('Dog \n \n "The dog name is puppy."'),
  ThreeLettersText('Cat \n \n "The cat is a very adorable animal."'),
  ThreeLettersText('un \n \n "He can run very fastly."'),
  ThreeLettersText('Fun \n \n "He\'s a fun person to be with."'),
  ThreeLettersText('Sun \n \n "The sun is shining brightly."'),
  ThreeLettersText('Son \n \n "She gave a birth to a son."'),
  ThreeLettersText('Hot \n \n "Nowadays it\'s very hot."'),
  ThreeLettersText('Big \n \n  "I  have a big idea." '),
  ThreeLettersText('Pig \n \n "The main course of the feast was roast suckling pig."'),
  ThreeLettersText('Red \n \n "My favourite colour is red."'),
  ThreeLettersText('See \n \n "I can see you."'),
  ThreeLettersText('Saw \n \n "I saw a town in the distance."'),
  ThreeLettersText('Say \n \n "She says she\'ll tell me the whole story if and when she chooses."'),
  ThreeLettersText('Sit \n \n "He was sitting in a chair next to the window."'),
  ThreeLettersText('Say \n \n "She says she\'ll tell me the whole story if and when she chooses." '),
  ThreeLettersText('Sat \n \n "I sat in the front of the busy."'),
  ThreeLettersText('Day \n \n "We\'re open seven days a week, 365 days a year."'),
  ThreeLettersText('Bin \n \n "We tried our best, but you can\'t win them all."'),
  ThreeLettersText('Van \n \n "We spent three hours locked in a police van."'),
  ThreeLettersText('Tap \n \n "She turned in the taps."'),
  ThreeLettersText('Pen \n \n "I want new pen for exam."'),
  ThreeLettersText('Old \n \n "Lived to be eighty years old."'),
  ThreeLettersText('Nap \n \n "You look like you could use a nap."'),
  ThreeLettersText('Mix \n \n "It mixes easily with cold or hot water to make a tasty, filling drink."'),
  ThreeLettersText('Log \n \n "Running along the beach, she stumbled on a log and fell on the sand."'),
  ThreeLettersText('Ice \n \n  "I want ice cream."'),
  ThreeLettersText('Hot \n \n "He hopped over the hot sand." '),
  ThreeLettersText('Get \n \n "She gets the trian to work every day."'),
  ThreeLettersText('For \n \n "I want new pen for examination."'),
  ThreeLettersText('Far \n \n  "The dog wandered far from home."'),
  ThreeLettersText('End \n \n "The report is due at the end of the month."'),
  ThreeLettersText('BOx \n \n "I took her a box of chocolates."'),
  ThreeLettersText('Fox \n \n "He\'s a wily old fox."'),
  ThreeLettersText('One \n \n "I have one good friend."'),
  ThreeLettersText('Two \n \n "I have two beautiful rings."'),
  ThreeLettersText('Ten \n \n "Rarely more than ten."'),
  ThreeLettersText('Teo \n \n "My sock has a hole in the toe."'),
  ThreeLettersText('Out \n \n "He went out to the garden."'),
  ThreeLettersText('Rat \n \n "A dirty old building infested by rats and mice."'),
  ThreeLettersText('Map \n \n "Map is very useful for travellers."'),
  ThreeLettersText('Mop \n \n "There was a woman mopping the stairs."'),
  ThreeLettersText('Ben \n \n "How to use Ben."'),
  ThreeLettersText('Hen \n \n "My hens have stopped laying."'),
  ThreeLettersText('Ink \n \n "Don\' t write in red ink."'),
  ThreeLettersText('Mat \n \n "Wipe your feet on the mat before you come inside."'),
  ThreeLettersText('Man \n \n "He is very strong man."'),
  ThreeLettersText('Art \n \n "I know something about mandala art."'),
  //----------------------------50------------------------------------
  ThreeLettersText('Arc \n \n "The arc of the rainbow reached from the sky to the top of the hill."'),
  ThreeLettersText('Ant \n \n "Ant have sensing power."'),
  ThreeLettersText('Top \n \n "I can\'t reach the top floor."'),
  ThreeLettersText('Tip \n \n "I\'ve a tip for the races."'),
  ThreeLettersText('Did \n \n "He did a car wheel."'),
  ThreeLettersText('Sir \n \n "Excuse me sir."'),
  ThreeLettersText('Are \n \n "Are you okay?." '),
  ThreeLettersText('You \n \n "How are you?."'),
  ThreeLettersText('Our \n \n  "Our national animal is tiger."'),
  ThreeLettersText('The \n \n "The students are hard working, and generally very intelligent." '),
  ThreeLettersText('Eye \n \n  "Eyes are very important organ in our body." '),
  ThreeLettersText('Add \n \n  "Add some sugar." '),
  ThreeLettersText('She \n \n "She is very simple."'),
  ThreeLettersText('His \n \n  "He bought his own house."'),
  ThreeLettersText('Him \n \n "John\'s aunt died suddenly and left him a surprisingly large sum."'),
  ThreeLettersText('Was \n \n "I was home last night."'),
  ThreeLettersText('Has \n \n "He has written a fascinating story."'),
  ThreeLettersText('Any \n \n "Any one have two pen."'),
  ThreeLettersText('Let \n \n "Let them go."'),
  ThreeLettersText('Try \n \n "I\'ll try again next year."'),
  ThreeLettersText('Cry \n \n "The childrens began to cry."'),
  ThreeLettersText('God \n \n  "God, I\'m glad you called."'),
  ThreeLettersText('Got \n \n "I got my son to repair the door."'),
  ThreeLettersText('Ear \n \n "He whispered something in her ear."'),
  ThreeLettersText('Bye \n \n "The time to say goodbye ."'),
  ThreeLettersText('Zip \n \n "He pulled the zip of his leather jacket down slightly."'),
  ThreeLettersText('Yes \n \n  "yes, I\'ll be ready for the test tomorrow."'),
  ThreeLettersText('Rid \n \n "I got rid of some old furniture by selling/giving it to my nephew." '),
  ThreeLettersText('Fat \n \n "Their cat is fat and lazy."'),
  ThreeLettersText('Key \n \n "The put the key in the door and entered."'),
  ThreeLettersText('Not \n \n "Iam not interested in dance."'),
  ThreeLettersText('Ask \n \n "I need to ask a question."'),
  ThreeLettersText('Bid \n \n "I bid against you."'),
  ThreeLettersText('Who \n \n "Who are you?."'),
  ThreeLettersText('How \n \n  "How are you? I am fine."'),
  ThreeLettersText('Out \n \n "I threw aside my mosquito net and jumped out of bed."'),
  ThreeLettersText('Cut \n \n "Don\'t cut the trees.."'),
  ThreeLettersText('Sad \n \n "Iam very sad Today."'),
  ThreeLettersText('Fan \n \n "They are both ardent Elvis fans."'),
  ThreeLettersText('Met \n \n "I met tom infront of the door."'),
  ThreeLettersText('Toy \n \n "The toys are beautiful."'),
  ThreeLettersText('Bee \n \n "A swarm of bee s flew into the garden."'),
  ThreeLettersText('Cub \n \n "She was joined by her two cubs."'),
  ThreeLettersText('Fix \n \n "He fixed the fence last weekend."'),
  ThreeLettersText('Jam \n \n  "I like to eat jam."'),
  ThreeLettersText('Job \n \n "He took a job as a waiter."'),

];
