
class Wordsletter {
  final String text;
  Wordsletter(this.text);
}

List<Wordsletter> wordsletters = [

  Wordsletter('Awesome \n \n "We had an awesome time at the concert."'),
  Wordsletter('Amazing \n \n "Causing great surprise or wonder, or very good."'),
  Wordsletter('Admirable \n \n"Her dedication to her work was admirable."'),
  Wordsletter('Adorable \n \n"Here she is with an adorable puppy."'),
  Wordsletter('Attention Grabbing \n \n"It pales when compared to the attention-grabbing first hour."'),
  Wordsletter('Astonishing \n \n"He showed an astonishing lack of concern for others."'),
  Wordsletter('Best \n \n"His modesty and sense of humor are his best qualities."'),
  Wordsletter('Brillinant \n \n "Her mother was a brilliant scientist." '),
  Wordsletter('Breath taking \n \n "They gave a breathtaking performance."'),
  Wordsletter('Champion \n \n "He was a champion for the working classes."'),
  Wordsletter('Commendable \n \n "Sparrow has acted with commendable speed."'),
  Wordsletter('Extraordinary \n \n "The researchers made an extraordinary discovery."'),
  Wordsletter('Exceptional \n \n "His translation is exceptional in its poetic quality."'),
  Wordsletter('Excellent \n \n "The meal looked and tasted excellent."'),
  Wordsletter('Effective\n \n "Simple antibiotics are effective against this organism."'),
  Wordsletter('Fabulous \n \n "I had a fabulous time."'),
  Wordsletter('Fantastic \n \n "Visions of a fantastic, maze-like building."'),
  Wordsletter('Fantabulous \n \n "What a fantabulous year this was for women on screen."'),
  Wordsletter ('First-class \n \n "I sent it by first-class mail."'),
  Wordsletter('Fine \n \n "The coin is struck in .986 fine gold."'),
  Wordsletter('Flawless \n \n "She looked so perfect and flawless and she seemed utterly smitten with Bernard."'),
  Wordsletter('Great \n \n "No one told you to move, you great lump! Stand still!."'),
  Wordsletter('High-quality \n \n "Senior staff set a good example by their own high-quality teaching."'),
  Wordsletter('Incomparable \n \n "Censorship still exists, but now its incomparable with what it was."'),
  Wordsletter('Imperative \n \n "Water is imperative for survival."'),
  Wordsletter('Incredible \n \n "The noise from the crowd was incredible."'),
  Wordsletter('Interesting \n \n "It will be very interesting to see what they come up with."'),
  Wordsletter('Invaluable \n \n "To still have that type of player around the scene would be invaluable."'),
  Wordsletter('Memorable \n \n "It was memorable, not for the car, but for the unfortunate timing of the even."'),
  Wordsletter('Mesmerizing \n \n "He spoke to us extemporaneously for at least two hours, weaving a mesmerizing tapestry of wisdom."'),
  Wordsletter('Magnificent \n \n "There s a magnificent view from the top!."'),
  Wordsletter('Mind-blowing \n \n "That is mind-blowing in its stupidity."'),
  Wordsletter('Outstanding \n \n "The outstanding balance must be paid by the end of the month."'),
  Wordsletter('Outperformed \n \n "The company has consistently outperformed its rivals this season."'),
  Wordsletter('Phenomenal \n \n "The crowds have flocked back, the feel-good factor has been phenomenal."'),
  Wordsletter('Perfect \n \n "He drew a perfect circle."'),
  Wordsletter('Remarkable \n \n "When you look at it like that, its a truly remarkable feat."'),
  Wordsletter('Reverberating \n \n "At night, screams could be heard reverberating around the walls of the buildings."'),
  Wordsletter('Super \n \n "Super! I ll see you later!."'),
  Wordsletter('Super-duper \n \n "They are both super-duper spellers."'),
  Wordsletter('Superb \n \n "They ve done a superb job."'),
  Wordsletter('Superior \n \n "It is vastly superior to the previous two films."'),
  Wordsletter('Supreme \n \n "With a supreme effort of will, I manage to look away from the large mirror."'),
  Wordsletter('Stupendous \n \n "There are stupendous views from the top floor."'),
  Wordsletter('Stunning \n \n "The view from the top of the cathedral is stunning."'),
  Wordsletter('Spectacular \n \n "you should see the film in 3D - it s spectacular."'),
  Wordsletter('Terrific \n \n "He lost a terrific amount of blood."'),
  Wordsletter('Tremendous \n \n "It involved a tremendous amount of work."'),
  Wordsletter('Wonderful \n \n "Was a wonderful party. You did a wonderful job."'),

];
